baseURL = 'https://jack-sides.com/'
languageCode = 'en-us'
title = 'Jack Sides'

[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10

[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "/assets/resume.pdf"
weight = 10